import type { Metadata } from "next";
import "./globals.css";
import { lato } from "./ui/fonts";
import { themeScript } from "./lib/theme-script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body
        className={`${lato.className} antialiased bg-white dark:bg-gray-900 transition-colors`}
      >
        {children}
      </body>
    </html>
  );
}
